

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx.h"
#include "includes.h"

/* Private define ------------------------------------------------------------*/
#define X_SHIFT_ADDR              80
#define Y_SHIFT_ADDR              100

#define X_BASE_ADDR               10
#define Y_BASE_ADDR               20
#define TAB_NAME_Y_POS            Y_BASE_ADDR

#define CH_NAME_X_POS             X_BASE_ADDR
#define TM0_NAME_X_POS            X_BASE_ADDR+X_SHIFT_ADDR
#define VOL0_NAME_X_POS           TM0_NAME_X_POS+X_SHIFT_ADDR
#define TM1_NAME_X_POS            VOL0_NAME_X_POS+X_SHIFT_ADDR
#define VOL1_NAME_X_POS           TM1_NAME_X_POS+X_SHIFT_ADDR
#define TM2_NAME_X_POS            VOL1_NAME_X_POS+X_SHIFT_ADDR
#define VOL2_NAME_X_POS           TM2_NAME_X_POS+X_SHIFT_ADDR
#define TM3_NAME_X_POS            VOL2_NAME_X_POS+X_SHIFT_ADDR
#define VOL3_NAME_X_POS           TM3_NAME_X_POS+X_SHIFT_ADDR
#define TM4_NAME_X_POS            VOL3_NAME_X_POS+X_SHIFT_ADDR
#define VOL4_NAME_X_POS           TM4_NAME_X_POS+X_SHIFT_ADDR

#define CH0_Y_POS          				TAB_NAME_Y_POS+Y_SHIFT_ADDR
#define CH1_Y_POS         				CH0_Y_POS+Y_SHIFT_ADDR
#define CH2_Y_POS         				CH1_Y_POS+Y_SHIFT_ADDR
#define CH3_Y_POS         				CH2_Y_POS+Y_SHIFT_ADDR

#define SCR_WIDTH                 84
#define SCR_HIGHT                 16
#define FONT_SIZE                 24
#define NUM_SIZE                  16
/* Private variables ---------------------------------------------------------*/
unsigned char Dac_Data_index[20] = {0};
unsigned char Dac_CH_index[4] = {0,1,2,3};

void LCD_play_init(void)
{
	LCD_Display_Dir(1);//∫·∆¡œ‘ æ
	LCD_Clear(WHITE);
	
	LCD_ShowString(CH_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"CH");
	LCD_ShowString(CH_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"CH0");
	LCD_ShowString(CH_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"CH1");
	LCD_ShowString(CH_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"CH2");
	LCD_ShowString(CH_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"CH3");
	
	LCD_ShowString(TM0_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"T0(ms)");
	LCD_ShowString(TM0_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM0_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM0_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM0_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");

	LCD_ShowString(VOL0_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"V0(mv)");
	LCD_ShowString(VOL0_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL0_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL0_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL0_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	
	LCD_ShowString(TM1_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"T1(ms)");
	LCD_ShowString(TM1_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM1_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM1_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM1_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	
	LCD_ShowString(VOL1_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"V1(mv)");
	LCD_ShowString(VOL1_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL1_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL1_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL1_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	
	LCD_ShowString(TM2_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"T2(ms)");
	LCD_ShowString(TM2_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM2_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM2_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM2_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	
	LCD_ShowString(VOL2_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"V2(mv)");
	LCD_ShowString(VOL2_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL2_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL2_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL2_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	
	LCD_ShowString(TM3_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"T3(ms)");
	LCD_ShowString(TM3_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM3_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM3_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM3_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	
	LCD_ShowString(VOL3_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"V3(mv)");
	LCD_ShowString(VOL3_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL3_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL3_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL3_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	
	LCD_ShowString(TM4_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"T4(ms)");
	LCD_ShowString(TM4_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM4_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM4_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	LCD_ShowString(TM4_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.1");
	
	LCD_ShowString(VOL4_NAME_X_POS,TAB_NAME_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"V4(mv)");
	LCD_ShowString(VOL4_NAME_X_POS,CH0_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL4_NAME_X_POS,CH1_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL4_NAME_X_POS,CH2_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");
	LCD_ShowString(VOL4_NAME_X_POS,CH3_Y_POS,SCR_WIDTH,SCR_HIGHT,FONT_SIZE,"0.2");

}	

//void LCD_play_Param(void)